version: "3.9"

services:
  spring_batch_flow:
    container_name: spring_batch_flow
    image: spring_batch_flow
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/batchDB
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    container_name: postgres_db
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=batchDB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
